import "./css/style.css";
import { setStatus, getStatus } from "@/app/api/status";
import StatusProvider from "@/context/StatusContext";

import localFont from "next/font/local";

const CodePro = localFont({
  src: "../public/fonts/CodePro/Code Pro Bold LC.otf",
  display: "swap",
  variable: "--font-codepro",
});

const DMSans = localFont({
  src: "../public/fonts/DMsans/DMSans-VariableFont_opsz,wght.ttf",
  display: "swap",
  variable: "--font-dmsans",
});

const Poppins = localFont({
  src: "../public/fonts/Poppins/Poppins-SemiBold.ttf",
  display: "swap",
  variable: "--font-poppin",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const status = await getStatus();
  return (
    <html lang="en">
      <body
        className={`${DMSans.variable} ${CodePro.variable} ${Poppins.variable} font-dmsans antialiased bg-white text-gray-900 tracking-tight`}
      >
        <StatusProvider status={status}>
          <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
            {children}
          </div>
        </StatusProvider>
      </body>
    </html>
  );
}
